### ISSUE TITLE
Create vis for comparion biomarker expressions across cells and datasets

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/hra-cell-type-populations-supporting-information#133]
From @katyb, 4/13/24: It would be great to have a graph like attached that shows the distribution of the #cells that have certain expression levels for the top 20-40 biomarkers.

TODOs:
 - @andreasbueckle create dataset (CSV) with: 
 ```
organ_id | organ_label | dataset_id | cell_id | cell_label | gene_label | mean_gene_expression_value
 ```
 - Uses https://lod.humanatlas.io/graph/hra-pop/v0.10.2/assets/atlas-enriched-dataset-graph.jsonld

@mginda renders density plot:
 - color area under curve by organ

**Comment by bherr2** [comment]
CSV Results are here: https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.10.2/reports/atlas/validation-b-mean-expression.csv

**Comment by bherr2** [comment]
Note I added tool and modality as well
