### ISSUE TITLE
Update bar graphs 

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/hra-cell-type-populations-supporting-information#134]
Work with Michael to make bar graphs, one per organ, split by trans and prot, to compare as cell summaries across, each bar is one dataset, stacked by CT, faceted by organ initially

Render vertical (optional), add organ-dataset_id labels, facet by tool, 
Use v.0.10.2: https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.10.2/reports/atlas/validation-v5.csv 

![image](https://github.com/cns-iu/hra-cell-type-populations-supporting-information/assets/22821046/f0830470-b3eb-46c5-95d3-e70f700b1eea)

**Comment by mginda** [comment]
All change requests have been implemented to clean up dataset labels. All plots have been exported as PDFs for Tracy.

Note: there is an issue with some dataset cell type percentages totaling to greater than 100% for heart and lung datasets. 
![heart_dataIssues](https://github.com/cns-iu/hra-cell-type-populations-supporting-information/assets/9054000/dfcd447f-4714-4467-9b0c-eba502798a60)
![lung_dataIssues](https://github.com/cns-iu/hra-cell-type-populations-supporting-information/assets/9054000/c06e6a25-3a9f-412f-a3aa-71a3026ebaf1)
