### ISSUE TITLE
application-a1 and validation-v1 through validation-v5 need column for UBERON ID for the organ and UBERON ID for the AS

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/hra-cell-type-populations-supporting-information#52]
Also reference organ ```VHM/F```reference organ

**Comment by bherr2** [comment]
Application A1 includes datasets that do not have a rui location and thus are not directly attributable to an organ. There may be roundabout ways to do it, but probably needs discussion to get right.

**Comment by andreasbueckle** [comment]
Yep! Ideally, we would be able to assign an organ for each dataset based on 
1. an API response in its source portal
2. its name
But it might be hard to generalize it to all datasets we might get.

**Comment by bherr2** [comment]
I can add Table S0's organ column ([Column W](https://docs.google.com/spreadsheets/d/1cwxztPg9sLq0ASjJ5bntivUk6dSKHsVyR1bE6bXvMkY/edit#gid=1529271254)) to the dataset and use that (maybe call it `reported_organ` or something) and use that for the datasets. This means we'll need to make organ a required column for S0 AND make sure the organ column is clean. But could be the best solution.

**Comment by bherr2** [comment]
Or we make it required. During "universe" construction, we can find that.

**Comment by andreasbueckle** [comment]
New Table S0 will have ```reported_organ``` column. User interface will make it necessary to indicate a supported organ.

**Comment by bherr2** [comment]
Added `reported_organ` to A1*. Added `organ` and `organId` to (via spatial placement/rui) in A2, Validation v1 (except extra1 which is aggregated at a higher level), and Validation v2.
