### ISSUE TITLE
Add Table S5 for tissue blocks an AS intersections

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/hra-cell-type-populations-supporting-information#54]
Each row is a RUI location, each column is an AS, and cells capture the intersection volumes of the TB with the AS

**Comment by bherr2** [comment]
Did a first pass on Table S5, but I think we need to talk about it a bit more to get it fully

**Comment by andreasbueckle** [comment]
Looks like the ```intersection_volume``` column currently just lists the volume of the **entire anatomical structure*** rather than the intersection volume **between the RUI location and the anatomical structure**. Could we fix that? Also, I suggest listing the intersection volume as a **percentage of the tissue block volume**.

**Comment by andreasbueckle** [comment]
Need to multiply ```percentage``` with ```as_volume```.
