### ISSUE TITLE
Add columns to validation-v5 edges and/or nodes 

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/hra-cell-type-populations-supporting-information#55]
Add 1 column per cell type and percentage of cell type (but keep cosine similarity) for source and target (or just node in node list)

**Comment by bherr2** [comment]
We'll need to review this one. I don't understand what percentage of cell type is referring to here...

**Comment by andreasbueckle** [comment]
In the edge list, each row is an edge between two datasets (`source` and `target`). To provide multi-dimensionality for the UMAP plot, we should add 1 column for each unique cell type in the experimental data for each dataset in each row. The value in each cell would then be the percentage of cell type in the `source` or `target` dataset, This could also be added to the node list instead to have fewer duplicate columns. For example:

```
source_dataset_id | target_dataset_id | cell_type_1_in_source | cell_type_2_in_source | cell_type_1_in_target | cell_type_2_in_target | ... | cosine_similarity
dataset1 | dataset2 | 0.2 | 0.8 | 0.5 | 0.5 | ... | 0.3
dataset2 | dataset3 | 0.5 | 0.5 | 0.15 | 0.85 | ... | 0.1
dataset1 | dataset3 | 0.2 | 0.8 | 0.15 | 0.85 | ... | 0.9
```

**Comment by bherr2** [comment]
@mginda please review above and let me know what you need.

Can this just be in the nodes file (or a totally different file as the edges in v5 are not really relevant for what you're doing I think...)? I also will likely not be able to make them separate columns without changing the process. I can however create a column with the individual cells separated by a delimeter and a parallel column with counts separated by a delimiter. Would that work? Or would a "long" format work (ie dataset_id, cell_id, percentage) work (this is actually the best format)?

**Comment by bherr2** [comment]
"long" form from SPARQL is easiest/best for me. If it needs to be transformed to 'wide' format, I can do that, but might be just as easy (if not easier) from R.

**Comment by bherr2** [comment]
Superceded by #56
