### ISSUE TITLE
Remove ```predicted_cell_type_population``` column in table S1?

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/hra-cell-type-populations-supporting-information#61]
With prediction now in its own report, I suggest we remove ```predicted_cell_type_population```, see query at https://github.com/cns-iu/hra-cell-type-populations-supporting-information/blob/d287243820f8791dbae367288b6b7a87d8a970c6/data-processor/queries/table-s1.rq#L40

**Comment by bherr2** [comment]
Sure. And ?predicted_rui_location (both say coming soon)

**Comment by andreasbueckle** [comment]
Yes, I suggest removing both. Thanks!

**Comment by andreasbueckle** [comment]
Yes to all. They are all part of the Atlas, so ```?excluded_from_atlas_construction``` is not needed.
