### ISSUE TITLE
Update verbiage in pop-up window for Application 1

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/hra-cell-type-populations-supporting-information#62]
In https://apps.humanatlas.io/ctpop/application-1.html, when a tissue block does not collider with an anatomical structure with an ```as-cell-summary```, I suggest writing:

```We identified no collisions between the tissue block and any anatomical structure with a cell type population as part of the Atlas. Please refer to (this table)[https://github.com/cns-iu/hra-cell-type-populations-supporting-information/blob/main/data/reports/table-s2.csv] for an overview of anatomical structures for which cell type populations exist in the Atlas.````

**Comment by bherr2** [comment]
Actually, sometimes there are collisions, but no as-cell-summaries and thus returns zero results later. Can you suggest something that covers both the cases?

**Comment by bherr2** [comment]
Well, actually, I guess that does kind of cover it.

**Comment by andreasbueckle** [comment]
We should also think about providing a breakdown of Atlas ```as-cell-summaries``` per organ. I think a simple table will do, like:
```as_name | as_iri |number_of_unique_cell_types | based_on_n_datasets```

So basically what we have in the ```as-cell-summaries```, just rendered as a table rather than JSON.
